"""post mention

Revision ID: a8ba7e4d38bf
Revises: 5a1f146db08e
Create Date: 2022-11-13 22:33:59.789000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ba7e4d38bf'
down_revision = '5a1f146db08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mention', sa.Column('recorddate', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mention', 'recorddate')
    # ### end Alembic commands ###
